language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - dennis.yee1@ncs.com.sg
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli
  - npm install -g now
script:
  - ng build --prod --base-href https://dennisyee94.github.io/bitcoin-order-app/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: d4d8af7b4a2a5fa44966901ab8f5ffeb3d0892cc
  local_dir: dist/bitcoin
  edge: true
  on:
    branch: development
